name: Unit tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18, 20 ]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install the Coach
      run: npm ci
    - name: Install latest Chrome
      uses: browser-actions/setup-chrome@v2
    - name: Lint
      run: npm run lint
    - name: Run unit tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: npm run test
